/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */

/**
 * @summary Root
 */
export type rootApiTestGetResponse200 = {
	data: unknown;
	status: 200;
};

export type rootApiTestGetResponseSuccess = rootApiTestGetResponse200 & {
	headers: Headers;
};
export type rootApiTestGetResponse = rootApiTestGetResponseSuccess;

export const getRootApiTestGetUrl = () => {
	return `/api/test`;
};

export const rootApiTestGet = async (options?: RequestInit): Promise<rootApiTestGetResponse> => {
	const res = await fetch(getRootApiTestGetUrl(), {
		...options,
		method: 'GET'
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: rootApiTestGetResponse['data'] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as rootApiTestGetResponse;
};
