/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
import { createQuery } from '@tanstack/svelte-query';
import type {
	CreateQueryOptions,
	CreateQueryResult,
	DataTag,
	QueryClient,
	QueryFunction,
	QueryKey
} from '@tanstack/svelte-query';

import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

/**
 * @summary Root
 */
export const rootApiTestGet = (options?: AxiosRequestConfig): Promise<AxiosResponse<unknown>> => {
	return axios.get(`/api/test`, options);
};

export const getRootApiTestGetQueryKey = () => {
	return [`/api/test`] as const;
};

export const getRootApiTestGetQueryOptions = <
	TData = Awaited<ReturnType<typeof rootApiTestGet>>,
	TError = AxiosError<unknown>
>(options?: {
	query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof rootApiTestGet>>, TError, TData>>;
	axios?: AxiosRequestConfig;
}) => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getRootApiTestGetQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof rootApiTestGet>>> = ({ signal }) =>
		rootApiTestGet({ signal, ...axiosOptions });

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof rootApiTestGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RootApiTestGetQueryResult = NonNullable<Awaited<ReturnType<typeof rootApiTestGet>>>;
export type RootApiTestGetQueryError = AxiosError<unknown>;

/**
 * @summary Root
 */

export function createRootApiTestGet<
	TData = Awaited<ReturnType<typeof rootApiTestGet>>,
	TError = AxiosError<unknown>
>(
	options?: {
		query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof rootApiTestGet>>, TError, TData>>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getRootApiTestGetQueryOptions(options);

	const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}
