/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
import { createQuery } from '@tanstack/svelte-query';
import type {
	CreateQueryOptions,
	CreateQueryResult,
	DataTag,
	QueryClient,
	QueryFunction,
	QueryKey
} from '@tanstack/svelte-query';

import { customInstance } from '.././axios';

/**
 * @summary Root
 */
export const rootApiTestGet = (signal?: AbortSignal) => {
	return customInstance<unknown>({ url: `/api/test`, method: 'GET', signal });
};

export const getRootApiTestGetQueryKey = () => {
	return [`/api/test`] as const;
};

export const getRootApiTestGetQueryOptions = <
	TData = Awaited<ReturnType<typeof rootApiTestGet>>,
	TError = unknown
>(options?: {
	query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof rootApiTestGet>>, TError, TData>>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getRootApiTestGetQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof rootApiTestGet>>> = ({ signal }) =>
		rootApiTestGet(signal);

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof rootApiTestGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RootApiTestGetQueryResult = NonNullable<Awaited<ReturnType<typeof rootApiTestGet>>>;
export type RootApiTestGetQueryError = unknown;

/**
 * @summary Root
 */

export function createRootApiTestGet<
	TData = Awaited<ReturnType<typeof rootApiTestGet>>,
	TError = unknown
>(
	options?: {
		query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof rootApiTestGet>>, TError, TData>>;
	},
	queryClient?: QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getRootApiTestGetQueryOptions(options);

	const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}
