/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
export type BodyLoginForAccessTokenApiLoginPostGrantType = string | null;

export type BodyLoginForAccessTokenApiLoginPostClientId = string | null;

export type BodyLoginForAccessTokenApiLoginPostClientSecret = string | null;

export interface BodyLoginForAccessTokenApiLoginPost {
	grant_type?: BodyLoginForAccessTokenApiLoginPostGrantType;
	username: string;
	password: string;
	scope?: string;
	client_id?: BodyLoginForAccessTokenApiLoginPostClientId;
	client_secret?: BodyLoginForAccessTokenApiLoginPostClientSecret;
}

export interface HTTPValidationError {
	detail?: ValidationError[];
}

/**
 * JWT token response schema.
 */
export interface Token {
	access_token: string;
	token_type: string;
}

/**
 * Schema for creating a new user.
 */
export interface UserCreate {
	email: string;
	/**
	 * Must contain uppercase, lowercase, digit, and special character
	 * @minLength 8
	 * @maxLength 15
	 */
	password: string;
}

/**
 * Schema for user public data (excludes password).
 */
export interface UserPublic {
	email: string;
	id: number;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
	loc: ValidationErrorLocItem[];
	msg: string;
	type: string;
}
