/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
import type {
	CreateMutationOptions,
	CreateMutationResult,
	CreateQueryOptions,
	CreateQueryResult,
	DataTag,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey
} from '@tanstack/svelte-query';
import { createMutation, createQuery } from '@tanstack/svelte-query';

import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import axios from 'axios';

import type {
	BodyLoginForAccessTokenApiLoginPost,
	HTTPValidationError,
	Token,
	UserCreate,
	UserPublic
} from '../superimpress.schemas';

/**
 * @summary Register User
 */
export const registerUserApiRegisterPost = (
	userCreate: UserCreate,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<UserPublic>> => {
	return axios.post(`/api/register`, userCreate, options);
};

export const getRegisterUserApiRegisterPostMutationOptions = <
	TError = AxiosError<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof registerUserApiRegisterPost>>,
		TError,
		{ data: UserCreate },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof registerUserApiRegisterPost>>,
	TError,
	{ data: UserCreate },
	TContext
> => {
	const mutationKey = ['registerUserApiRegisterPost'];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof registerUserApiRegisterPost>>,
		{ data: UserCreate }
	> = (props) => {
		const { data } = props ?? {};

		return registerUserApiRegisterPost(data, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type RegisterUserApiRegisterPostMutationResult = NonNullable<
	Awaited<ReturnType<typeof registerUserApiRegisterPost>>
>;
export type RegisterUserApiRegisterPostMutationBody = UserCreate;
export type RegisterUserApiRegisterPostMutationError = AxiosError<HTTPValidationError>;

/**
 * @summary Register User
 */
export const createRegisterUserApiRegisterPost = <
	TError = AxiosError<HTTPValidationError>,
	TContext = unknown
>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof registerUserApiRegisterPost>>,
			TError,
			{ data: UserCreate },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof registerUserApiRegisterPost>>,
	TError,
	{ data: UserCreate },
	TContext
> => {
	const mutationOptions = getRegisterUserApiRegisterPostMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
/**
 * @summary Login For Access Token
 */
export const loginForAccessTokenApiLoginPost = (
	bodyLoginForAccessTokenApiLoginPost: BodyLoginForAccessTokenApiLoginPost,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<Token>> => {
	const formUrlEncoded = new URLSearchParams();
	if (
		bodyLoginForAccessTokenApiLoginPost.grant_type !== undefined &&
		bodyLoginForAccessTokenApiLoginPost.grant_type !== null
	) {
		formUrlEncoded.append(`grant_type`, bodyLoginForAccessTokenApiLoginPost.grant_type);
	}
	formUrlEncoded.append(`username`, bodyLoginForAccessTokenApiLoginPost.username);
	formUrlEncoded.append(`password`, bodyLoginForAccessTokenApiLoginPost.password);
	if (bodyLoginForAccessTokenApiLoginPost.scope !== undefined) {
		formUrlEncoded.append(`scope`, bodyLoginForAccessTokenApiLoginPost.scope);
	}
	if (
		bodyLoginForAccessTokenApiLoginPost.client_id !== undefined &&
		bodyLoginForAccessTokenApiLoginPost.client_id !== null
	) {
		formUrlEncoded.append(`client_id`, bodyLoginForAccessTokenApiLoginPost.client_id);
	}
	if (
		bodyLoginForAccessTokenApiLoginPost.client_secret !== undefined &&
		bodyLoginForAccessTokenApiLoginPost.client_secret !== null
	) {
		formUrlEncoded.append(`client_secret`, bodyLoginForAccessTokenApiLoginPost.client_secret);
	}

	return axios.post(`/api/login`, formUrlEncoded, options);
};

export const getLoginForAccessTokenApiLoginPostMutationOptions = <
	TError = AxiosError<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof loginForAccessTokenApiLoginPost>>,
		TError,
		{ data: BodyLoginForAccessTokenApiLoginPost },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof loginForAccessTokenApiLoginPost>>,
	TError,
	{ data: BodyLoginForAccessTokenApiLoginPost },
	TContext
> => {
	const mutationKey = ['loginForAccessTokenApiLoginPost'];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof loginForAccessTokenApiLoginPost>>,
		{ data: BodyLoginForAccessTokenApiLoginPost }
	> = (props) => {
		const { data } = props ?? {};

		return loginForAccessTokenApiLoginPost(data, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type LoginForAccessTokenApiLoginPostMutationResult = NonNullable<
	Awaited<ReturnType<typeof loginForAccessTokenApiLoginPost>>
>;
export type LoginForAccessTokenApiLoginPostMutationBody = BodyLoginForAccessTokenApiLoginPost;
export type LoginForAccessTokenApiLoginPostMutationError = AxiosError<HTTPValidationError>;

/**
 * @summary Login For Access Token
 */
export const createLoginForAccessTokenApiLoginPost = <
	TError = AxiosError<HTTPValidationError>,
	TContext = unknown
>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof loginForAccessTokenApiLoginPost>>,
			TError,
			{ data: BodyLoginForAccessTokenApiLoginPost },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof loginForAccessTokenApiLoginPost>>,
	TError,
	{ data: BodyLoginForAccessTokenApiLoginPost },
	TContext
> => {
	const mutationOptions = getLoginForAccessTokenApiLoginPostMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
/**
 * @summary Read Users Me
 */
export const readUsersMeApiUsersMeGet = (
	options?: AxiosRequestConfig
): Promise<AxiosResponse<UserPublic>> => {
	return axios.get(`/api/users/me/`, options);
};

export const getReadUsersMeApiUsersMeGetQueryKey = () => {
	return [`/api/users/me/`] as const;
};

export const getReadUsersMeApiUsersMeGetQueryOptions = <
	TData = Awaited<ReturnType<typeof readUsersMeApiUsersMeGet>>,
	TError = AxiosError<unknown>
>(options?: {
	query?: Partial<
		CreateQueryOptions<Awaited<ReturnType<typeof readUsersMeApiUsersMeGet>>, TError, TData>
	>;
	axios?: AxiosRequestConfig;
}) => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getReadUsersMeApiUsersMeGetQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof readUsersMeApiUsersMeGet>>> = ({
		signal
	}) => readUsersMeApiUsersMeGet({ signal, ...axiosOptions });

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof readUsersMeApiUsersMeGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ReadUsersMeApiUsersMeGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof readUsersMeApiUsersMeGet>>
>;
export type ReadUsersMeApiUsersMeGetQueryError = AxiosError<unknown>;

/**
 * @summary Read Users Me
 */

export function createReadUsersMeApiUsersMeGet<
	TData = Awaited<ReturnType<typeof readUsersMeApiUsersMeGet>>,
	TError = AxiosError<unknown>
>(
	options?: {
		query?: Partial<
			CreateQueryOptions<Awaited<ReturnType<typeof readUsersMeApiUsersMeGet>>, TError, TData>
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getReadUsersMeApiUsersMeGetQueryOptions(options);

	const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}
