/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Super Impress
 * OpenAPI spec version: 0.1.0
 */
import type {
	CreateMutationOptions,
	CreateMutationResult,
	CreateQueryOptions,
	CreateQueryResult,
	DataTag,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey
} from '@tanstack/svelte-query';
import { createMutation, createQuery } from '@tanstack/svelte-query';

import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import axios from 'axios';

import type {
	BodyLoginUser,
	HTTPValidationError,
	Token,
	UserCreate,
	UserPublic
} from '../superimpress.schemas';

/**
 * @summary Register User
 */
export const registerUser = (
	userCreate: UserCreate,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<UserPublic>> => {
	return axios.post(`/api/register`, userCreate, options);
};

export const getRegisterUserMutationOptions = <
	TError = AxiosError<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof registerUser>>,
		TError,
		{ data: UserCreate },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof registerUser>>,
	TError,
	{ data: UserCreate },
	TContext
> => {
	const mutationKey = ['registerUser'];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof registerUser>>,
		{ data: UserCreate }
	> = (props) => {
		const { data } = props ?? {};

		return registerUser(data, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type RegisterUserMutationResult = NonNullable<Awaited<ReturnType<typeof registerUser>>>;
export type RegisterUserMutationBody = UserCreate;
export type RegisterUserMutationError = AxiosError<HTTPValidationError>;

/**
 * @summary Register User
 */
export const createRegisterUser = <TError = AxiosError<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof registerUser>>,
			TError,
			{ data: UserCreate },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof registerUser>>,
	TError,
	{ data: UserCreate },
	TContext
> => {
	const mutationOptions = getRegisterUserMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
/**
 * @summary Login User
 */
export const loginUser = (
	bodyLoginUser: BodyLoginUser,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<Token>> => {
	const formUrlEncoded = new URLSearchParams();
	if (bodyLoginUser.grant_type !== undefined && bodyLoginUser.grant_type !== null) {
		formUrlEncoded.append(`grant_type`, bodyLoginUser.grant_type);
	}
	formUrlEncoded.append(`username`, bodyLoginUser.username);
	formUrlEncoded.append(`password`, bodyLoginUser.password);
	if (bodyLoginUser.scope !== undefined) {
		formUrlEncoded.append(`scope`, bodyLoginUser.scope);
	}
	if (bodyLoginUser.client_id !== undefined && bodyLoginUser.client_id !== null) {
		formUrlEncoded.append(`client_id`, bodyLoginUser.client_id);
	}
	if (bodyLoginUser.client_secret !== undefined && bodyLoginUser.client_secret !== null) {
		formUrlEncoded.append(`client_secret`, bodyLoginUser.client_secret);
	}

	return axios.post(`/api/login`, formUrlEncoded, options);
};

export const getLoginUserMutationOptions = <
	TError = AxiosError<HTTPValidationError>,
	TContext = unknown
>(options?: {
	mutation?: CreateMutationOptions<
		Awaited<ReturnType<typeof loginUser>>,
		TError,
		{ data: BodyLoginUser },
		TContext
	>;
	axios?: AxiosRequestConfig;
}): CreateMutationOptions<
	Awaited<ReturnType<typeof loginUser>>,
	TError,
	{ data: BodyLoginUser },
	TContext
> => {
	const mutationKey = ['loginUser'];
	const { mutation: mutationOptions, axios: axiosOptions } = options
		? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, axios: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof loginUser>>,
		{ data: BodyLoginUser }
	> = (props) => {
		const { data } = props ?? {};

		return loginUser(data, axiosOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type LoginUserMutationResult = NonNullable<Awaited<ReturnType<typeof loginUser>>>;
export type LoginUserMutationBody = BodyLoginUser;
export type LoginUserMutationError = AxiosError<HTTPValidationError>;

/**
 * @summary Login User
 */
export const createLoginUser = <TError = AxiosError<HTTPValidationError>, TContext = unknown>(
	options?: {
		mutation?: CreateMutationOptions<
			Awaited<ReturnType<typeof loginUser>>,
			TError,
			{ data: BodyLoginUser },
			TContext
		>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient
): CreateMutationResult<
	Awaited<ReturnType<typeof loginUser>>,
	TError,
	{ data: BodyLoginUser },
	TContext
> => {
	const mutationOptions = getLoginUserMutationOptions(options);

	return createMutation(() => ({ ...mutationOptions, queryClient }));
};
/**
 * @summary Read Current User
 */
export const readCurrentUser = (
	options?: AxiosRequestConfig
): Promise<AxiosResponse<UserPublic>> => {
	return axios.get(`/api/users/me/`, options);
};

export const getReadCurrentUserQueryKey = () => {
	return [`/api/users/me/`] as const;
};

export const getReadCurrentUserQueryOptions = <
	TData = Awaited<ReturnType<typeof readCurrentUser>>,
	TError = AxiosError<unknown>
>(options?: {
	query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof readCurrentUser>>, TError, TData>>;
	axios?: AxiosRequestConfig;
}) => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getReadCurrentUserQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof readCurrentUser>>> = ({ signal }) =>
		readCurrentUser({ signal, ...axiosOptions });

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof readCurrentUser>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ReadCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof readCurrentUser>>>;
export type ReadCurrentUserQueryError = AxiosError<unknown>;

/**
 * @summary Read Current User
 */

export function createReadCurrentUser<
	TData = Awaited<ReturnType<typeof readCurrentUser>>,
	TError = AxiosError<unknown>
>(
	options?: {
		query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof readCurrentUser>>, TError, TData>>;
		axios?: AxiosRequestConfig;
	},
	queryClient?: QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getReadCurrentUserQueryOptions(options);

	const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}
